name: 👗 New spritepack
description: 🙋 Suggest a new spritepack to be added
title: "👗 Spritepack: "
labels: ["spritepack"]
body:
  - type: markdown
    attributes:
      value: |
        ### Thank you for your suggestion!

        We appreciate everyone's contribution. However, before you continue,
        please take a moment to check if your suggested spritepack:
        - is public (available by a public link; not 'DM me for link') or its
          author (*every* author if there are multiple) allows sharing it publicly
        - has no NSFW content (e.g. explicit naked Monika's body)
        - has no offensive content (e.g. hate symbols, hate speech, etc.)

        > [!NOTE]
        > While we respect your choice of entered spritepack name/tags/authors,
        > we will also check the spritepack content and correct how we see it fit.
        > Thank you for understanding.

  - type: input
    id: spritepack-name
    attributes:
      label: Spritepack name
      description: Enter the name of the spritepack
    validations:
      required: true

  - type: input
    id: author-name
    attributes:
      label: Author name(s)
      description: |
        Enter the name(s) of the author(s) of the spritepack
    validations:
      required: true

  - type: input
    id: tags
    attributes:
      label: Suggested tag(s)
      description: |
        Enter the desired tag(s) for this spritepack, do not include 'spritepack' itself
    validations:
      required: false

  - type: textarea
    id: spritepack-links
    attributes:
      label: Links to this spritepack
      description: |
        Enter links to this spritepack, at least one link to download as well as Discord links, Github, links to FAQ etc.

  - type: checkboxes
    id: claims-special
    attributes:
      label: Disclosures
      description: |
        Please select everything that applies
      options:
        - label: This spritepack is a commission
          required: false

  - type: checkboxes
    id: claims-checks
    attributes:
      label: Some final checks
      description: |
        By submitting the spritepack to our content list, you claim the following:
      options:
        - label: This spritepack is public OR we as mod.mon.icu maintainers are allowed to share it
          required: true
        - label: This spritepack is not NSFW and does not include offensive content
          required: true
        - label: This spritepack is tested and has no known serious issues
          required: true
